// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrwq9UiyLAvaPRdb7vIobJKDzZo2lavPg',
    appId: '1:748679454944:web:644ef18602205109343085',
    messagingSenderId: '748679454944',
    projectId: 'qraft-e8a1d',
    authDomain: 'qraft-e8a1d.firebaseapp.com',
    storageBucket: 'qraft-e8a1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrwq9UiyLAvaPRdb7vIobJKDzZo2lavPg',
    appId: '1:748679454944:android:644ef18602205109343085',
    messagingSenderId: '748679454944',
    projectId: 'qraft-e8a1d',
    storageBucket: 'qraft-e8a1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwq9UiyLAvaPRdb7vIobJKDzZo2lavPg',
    appId: '1:748679454944:ios:644ef18602205109343085',
    messagingSenderId: '748679454944',
    projectId: 'qraft-e8a1d',
    storageBucket: 'qraft-e8a1d.firebasestorage.app',
    iosBundleId: 'co.gothcorp.qraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrwq9UiyLAvaPRdb7vIobJKDzZo2lavPg',
    appId: '1:748679454944:ios:644ef18602205109343085',
    messagingSenderId: '748679454944',
    projectId: 'qraft-e8a1d',
    storageBucket: 'qraft-e8a1d.firebasestorage.app',
    iosBundleId: 'co.gothcorp.qraft',
  );
}